/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bnoovyjuxymvycszljty"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJub292eWp1eHltdnljc3psanR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1MTQxNDQsImV4cCI6MjA5MzA5MDE0NH0.uMc2OTVd_7uo5-1JR4TgmDyHBZE4a9C0ey-qZpQnv0s"